version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/builds/desktop"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/php"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/liquidsoap"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/docker/icecast"
    schedule:
      interval: "weekly"
